server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/novel_manage_system?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: novel_manage_system
    password: novel_manage_system

logging:
#  config: classpath:log4j.xml
  level:
    com.longlin.novel: info